name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: jethrodaniel/setup-zig@fix-caching
        with:
          version: 0.12.0-dev.3192+e2cbbd0c2

      - name: Build
        run: zig build

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jethrodaniel/setup-zig@fix-caching
        with:
          version: 0.12.0-dev.3192+e2cbbd0c2

      - name: Build
        run: zig build release

      - name: Github Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: zig-out/release/*
